---

version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: 'www-data'
                uid: 1000
        image: laravel
        container_name: laravel-app
        working_dir: /var/www
        ports:
            - 8000:8000
            - 5173:5173
        command: 'php artisan serve --host=0.0.0.0'
        environment:
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www'
            - './bootstrap/cache:/var/www/html/bootstrap/cache'
            - './storage:/var/www/html/storage'
        networks:
            - laravel
        depends_on:
            - mysql
        env_file:
            - .env

    mysql:
        image: 'mysql:latest'
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 'Asdf@1234'
            MYSQL_DATABASE: 'pninventory'
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql:
        driver: local
