---

version: 3

services:
    web:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        command: 'npx concurrently "npm run dev" "php artisan serve --host=0.0.0.0 --port=8000"'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - './bootstrap/cache:/var/www/html/bootstrap/cache'
            - './storage:/var/www/html/storage'
        networks:
            - sail
        depends_on:
            - pgsql
        env_file:
            - .env

    pgsql:
        image: 'postgres:15'
        environment:
            PGPASSWORD: 'postgres'
            POSTGRES_DB: 'pninventory_production'
            POSTGRES_USER: 'postgres'
            POSTGRES_HOST_AUTH_METHOD: 'md5'
            POSTGRES_PASSWORD: 'postgres'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'

volumes:
    sail-pgsql:
        driver: local
